version: 2

models:
  - name: stg_products
    columns:
      - name: product_id
        tests:
          - unique
          - not_null
      - name: unit_price
        tests:
          - not_null
      - name: category
        tests:
          - not_null
          - accepted_values:
              values: ['ELECTRONICS', 'GROCERIES', 'HOME APPLIANCES', 'CLOTHING', 'BEAUTY']

  - name: stg_suppliers
    columns:
      - name: supplier_id
        tests:
          - unique
          - not_null
      - name: supplier_name
        tests:
          - not_null

  - name: stg_warehouses
    columns:
      - name: warehouse_id
        tests:
          - unique
          - not_null
      - name: city
        tests:
          - not_null

  - name: stg_stores
    columns:
      - name: store_id
        tests:
          - unique
          - not_null
      - name: region
        tests:
          - not_null
          - accepted_values:
              values: ['SOUTH', 'EAST', 'WEST', 'MIDWEST', 'NORTHEAST', 'NORTHWEST', 'SOUTHEAST', 'SOUTHWEST']

  - name: stg_sales
    columns:
      - name: transaction_id
        tests:
          - unique
          - not_null
      - name: quantity_sold
        tests:
          - not_null
      - name: sale_amount
        tests:
          - not_null
      - name: unit_price
        tests:
          - not_null

  - name: stg_shipments
    columns:
      - name: shipment_id
        tests:
          - unique
          - not_null
      - name: carrier
        tests:
          - not_null
          - accepted_values:
              values: ['FEDEX', 'UPS', 'DHL', 'USPS']

  - name: stg_inventory
    columns:
      - name: product_id
        tests:
          - not_null
      - name: warehouse_id
        tests:
          - not_null
      - name: quantity_available
        tests:
          - not_null
