version: 2

sources:
  - name: raw
    database: SUPPLYCHAIN360
    schema: RAW
    tables:
      - name: PRODUCTS
      - name: SUPPLIERS
      - name: WAREHOUSES
      - name: INVENTORY
      - name: SHIPMENTS

  - name: sheets
    database: SUPPLYCHAIN360
    schema: SHEETS
    tables:
      - name: SHEET1

  - name: supabase
    database: SUPPLYCHAIN360
    schema: SUPABASE
    tables:
      - name: SALES
